server:
  port: 8282
spring:
  security:
    user:
      name: nipun
      password: nipun123
      roles: ADMIN,USER

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE
    authorization:
      check-token-access: permitAll