server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://student.ck6530zwhj6f.ap-south-1.rds.amazonaws.com:3306/student?createDatabaseIfNotExist=true
    username: admin
    password: colombocs
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace